version: '3.1'

services:
  php_app:
    build: php_app
    container_name: php_app
    restart: always
    ports:
      - 80:80   
    networks: 
      - network 
    depends_on: [db]
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: faesa123
      MYSQL_DATABASE: demo   
      MYSQL_HOST: db  
    ports: 
        - 00:33060  
    networks: 
        - network        
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks: 
        - network
    depends_on: [db]  
networks:
  network:
    driver: bridge 
   


    # mysql -uroot -p